pre-commit:
  parallel: true

  commands:
    go-fmt:
      glob: "**/*.go"
      root: backend
      run: gofumpt -d -l -e {staged_files}

    go-lint:
      glob: "**/*.go"
      root: backend
      run: golangci-lint run {staged_files}

    python-fmt:
      glob: "**/*.py"
      root: ai
      run: ruff format --check {staged_files}

    python-lint:
      glob: "**/*.py"
      root: ai
      run: ruff check {staged_files}

    python-types:
      glob: "**/*.py"
      root: ai
      run: uv run mypy .

# pre-push:
#   parallel: true

#   commands:
#     test:
#       root: backend
#       run: go test -race ./...

#     build:
#       root: backend
#       run: go build ./...

#     python-tests:
#       root: ai
#       run: uv run pytest

#     python-build:
#       root: ai
#       run: uv build
