providers:
  file:
    filename: /etc/traefik/dynamic.yaml

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: false
  insecure: false

ping:
  entryPoint: web

log:
  level: INFO

accessLog: {}
