export const reasoningStyles = {
  trigger: "aui-reasoning-trigger group/trigger text-muted-foreground hover:text-foreground flex max-w-[75%] items-center gap-2 py-1 text-sm transition-colors",
  triggerIcon: "aui-reasoning-trigger-icon size-4 shrink-0",
  triggerLabel: "aui-reasoning-trigger-label-wrapper relative inline-block leading-none",
  triggerShimmer: "aui-reasoning-trigger-shimmer shimmer pointer-events-none absolute inset-0 motion-reduce:animate-none",
  triggerChevron: "aui-reasoning-trigger-chevron mt-0.5 size-4 shrink-0 transition-transform duration-(--animation-duration) ease-out group-data-[state=closed]/trigger:-rotate-90 group-data-[state=open]/trigger:rotate-0",
  content: "aui-reasoning-content text-muted-foreground relative overflow-hidden text-sm outline-none group/collapsible-content ease-out data-[state=closed]:animate-collapsible-up data-[state=open]:animate-collapsible-down data-[state=closed]:fill-mode-forwards data-[state=closed]:pointer-events-none data-[state=open]:duration-(--animation-duration) data-[state=closed]:duration-(--animation-duration)",
  fade: "aui-reasoning-fade pointer-events-none absolute inset-x-0 bottom-0 z-10 h-8 bg-[linear-gradient(to_top,var(--color-background),transparent)] group-data-[variant=muted]/reasoning-root:bg-[linear-gradient(to_top,hsl(var(--muted)/0.5),transparent)] fade-in-0 animate-in group-data-[state=open]/collapsible-content:animate-out group-data-[state=open]/collapsible-content:fade-out-0 group-data-[state=open]/collapsible-content:delay-[calc(var(--animation-duration)*0.75)] group-data-[state=open]/collapsible-content:fill-mode-forwards duration-(--animation-duration) group-data-[state=open]/collapsible-content:duration-(--animation-duration)",
  text: "aui-reasoning-text relative z-0 max-h-64 space-y-4 overflow-y-auto ps-6 pt-2 pb-2 leading-relaxed transform-gpu transition-[transform,opacity] group-data-[state=open]/collapsible-content:animate-in group-data-[state=closed]/collapsible-content:animate-out group-data-[state=open]/collapsible-content:fade-in-0 group-data-[state=closed]/collapsible-content:fade-out-0 group-data-[state=open]/collapsible-content:slide-in-from-top-4 group-data-[state=closed]/collapsible-content:slide-out-to-top-4 group-data-[state=open]/collapsible-content:duration-(--animation-duration) group-data-[state=closed]/collapsible-content:duration-(--animation-duration)",
} as const
