export const attachmentStyles = {
  root: "aui-attachment-root relative",
  rootImage: "aui-attachment-root-composer only:*:first:size-24",
  previewTrigger: "aui-attachment-preview-trigger hover:bg-accent/50 cursor-pointer transition-colors",
  previewDialogContent: "aui-attachment-preview-dialog-content [&>button]:bg-foreground/60 [&_svg]:text-background [&>button]:hover:[&_svg]:text-destructive p-2 sm:max-w-3xl [&>button]:rounded-full [&>button]:p-1 [&>button]:opacity-100 [&>button]:ring-0!",
  previewWrapper: "aui-attachment-preview bg-background relative mx-auto flex max-h-[80dvh] w-full items-center justify-center overflow-hidden",
  previewImage: "block h-auto max-h-[80vh] w-auto max-w-full object-contain",
  previewImageLoaded: "aui-attachment-preview-image-loaded",
  previewImageLoading: "aui-attachment-preview-image-loading invisible",
  tile: "aui-attachment-tile bg-muted size-14 cursor-pointer overflow-hidden rounded-[calc(var(--composer-radius)-var(--composer-padding))] border transition-opacity hover:opacity-75",
  tileRemove: "aui-attachment-tile-remove text-muted-foreground hover:[&_svg]:text-destructive absolute end-1.5 top-1.5 size-3.5 rounded-full bg-white opacity-100 shadow-sm hover:bg-white! [&_svg]:text-black",
  removeIcon: "aui-attachment-remove-icon size-3 dark:stroke-[2.5px]",
  avatar: "aui-attachment-tile-avatar h-full w-full rounded-none",
  avatarImage: "aui-attachment-tile-image object-cover",
  fallbackIcon: "aui-attachment-tile-fallback-icon text-muted-foreground size-8",
  userMessageContainer: "aui-user-message-attachments-end col-span-full col-start-1 row-start-1 flex w-full flex-row justify-end gap-2",
  composerContainer: "aui-composer-attachments flex w-full flex-row items-center gap-2 overflow-x-auto empty:hidden",
  addButton: "aui-composer-add-attachment hover:bg-muted-foreground/15 dark:border-muted-foreground/15 dark:hover:bg-muted-foreground/30 size-8 rounded-full p-1 text-xs font-semibold",
  addIcon: "aui-attachment-add-icon size-5 stroke-[1.5px]",
} as const
