name: CI Backend

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # later will be separated into different CIs on each service
      - name: Find and test services
        run: |
          for dir in backend/*/; do
            if [ -f "$dir/go.mod" ]; then
              echo "Testing $dir"
              cd $dir
              go mod download
              go test -race ./...
              go build ./...
              cd -
            fi
          done

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: backend
