name: CI Frontend

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  ci-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      # later will be separated into different CIs on each app
      - name: Find, lint, test and build apps
        run: |
          for dir in frontend/*/; do
            if [ -f "${dir}package.json" ]; then
              echo "Building $dir"
              cd "$dir"
              npm ci
              npm run lint
              npm run test
              npm run build
              cd -
            fi
          done
